sudo: required

language: generic

services:
    - docker

before_install:
    - echo "start creating an image with dockerfile"
    - docker build -t idavid29/docker-react-app -f Dockerfile.dev ./

script:
    - docker run -e CI=true idavid29/docker-react-app npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: 'ap-northeast-2'
    app: 'Dockerreactapp'
    env: 'Dockerreactapp-env'
    bucket_name: 'elasticbeanstalk-ap-northeast-2-101769651124'
    bucket_path: 'Dockerreactapp'
    on:
        branch: master
access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_ACCESS_KEY
